### ISSUE TITLE
这个项目很有意思，还有没有其它算法？

### ISSUE THREAD

**Issue by bk111** [houbb/nlp-hanzi-similar#1]
C:\Users\Tom\Downloads\similar_python\similar>python main1.py
酒 洒
总分：19.8, 总权重: 26, 结果:0.7615384615384616
四角编码：8.0
汉字结构：10
偏旁部首：0
笔画数：1.8

C:\Users\Tom\Downloads\similar_python\similar>python main1.py
未 末
总分：26.0, 总权重: 26, 结果:1.0
四角编码：8.0
汉字结构：10
偏旁部首：6
笔画数：2.0

C:\Users\Tom\Downloads\similar_python\similar>python main1.py
末 来
总分：25.428571428571427, 总权重: 26, 结果:0.978021978021978
四角编码：8.0
汉字结构：10
偏旁部首：6
笔画数：1.4285714285714286

**Comment by houbb** [comment]
汉字相似度的算法不多，资料很少。
这个是有小伙伴研究生论文用到，我临时写的。仅供参考



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: bk111 ***@***.***&gt;
发送时间: 2022年3月3日 08:25
收件人: houbb/nlp-hanzi-similar ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [houbb/nlp-hanzi-similar] 这个项目很有意思，还有没有其它算法？ (Issue #1)





 
C:\Users\Tom\Downloads\similar_python\similar&gt;python main1.py
 酒 洒
 总分：19.8, 总权重: 26, 结果:0.7615384615384616
 四角编码：8.0
 汉字结构：10
 偏旁部首：0
 笔画数：1.8
 
C:\Users\Tom\Downloads\similar_python\similar&gt;python main1.py
 未 末
 总分：26.0, 总权重: 26, 结果:1.0
 四角编码：8.0
 汉字结构：10
 偏旁部首：6
 笔画数：2.0
 
C:\Users\Tom\Downloads\similar_python\similar&gt;python main1.py
 末 来
 总分：25.428571428571427, 总权重: 26, 结果:0.978021978021978
 四角编码：8.0
 汉字结构：10
 偏旁部首：6
 笔画数：1.4285714285714286
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
