### ISSUE TITLE
太好了，正是需要的工具

### ISSUE THREAD

**Issue by finch-f** [houbb/nlp-hanzi-similar#2]
我也是因为要做语言认知的研究找到的这里，非常感谢~

要是有论文可以引用就好了~

**Comment by houbb** [comment]
暂无论文，实现是根据多篇论文，我自行实现的。

祝使用愉快。

**Comment by houbb** [comment]
没论文，我做的实现，实现本身理论参考了多篇论文。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: finch ***@***.***&gt;
发送时间: 2022年4月20日 21:20
收件人: houbb/nlp-hanzi-similar ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [houbb/nlp-hanzi-similar] 太好了，正是需要的工具 (Issue #2)





 
我也是因为要做语言认知的研究找到的这里，非常感谢~
 
要是有论文可以引用就好了~
