### ISSUE TITLE
Python 最好将取字典方式，换成get方法

### ISSUE THREAD

**Issue by xyanyue** [houbb/nlp-hanzi-similar#3]
valueOne = hanzijiegouDict[charOne];   ==> valueOne = hanzijiegouDict.get(charOne,0);
因为charOne 可能不存在，避免python 报 “KeyError”

**Comment by houbb** [comment]
感谢提醒，python 接触的不多，是一个演示的例子。

给非 java 的小伙伴提供一下思路~~
