### ISSUE TITLE
无偏旁结构的字的相似度

### ISSUE THREAD

**Issue by lilipopololo** [houbb/nlp-hanzi-similar#4]
作者您好，我目前做形近字相关的内容，感谢您在汉字相似度的贡献。
我发现您使用四个字典，分别在笔画数、偏旁、结构数以及四角号码几个方面评价字的相似度，但是例如习、刁等无偏旁部首的单字没哟在偏旁字典中出现，以至于其偏旁部首的相似度为0（实际上无法评价），并且总相似度较低（74%），在遇到这种情况时是否改重新设置权重。

**Comment by lilipopololo** [comment]
没想到两个字偏旁不同

**Comment by lilipopololo** [comment]
不过存在一些问题譬如危这个字没有找到偏旁

**Comment by houbb** [comment]
嗯，后续可以加一个拆字的相似度权重。

我有时间加一下。
